### ISSUE TITLE
About the Chinese Translations.

### ISSUE THREAD

**Issue by QuasarQBH** [mythridium/music#1]
**Thank you for created this mod, I very like it.**
I found the mod has been translated to chinese,nice work!!!
 But I found an incorrect translation,"Bard",now in game it is wrong word "巴德", the right translation is "**吟游诗人**".
Thank you for created this mod so much!

**Comment by mythridium** [comment]
@QuasarQBH 

Thanks so much for reporting the incorrect translation, if you find anymore, please feel free to create more issues and I'll get them fixed.

From what google translate tells me, both simplified and traditional Chinese use the translation you provided so I replaced the text for both languages.

Hopefully that is all correct now.

Thanks for playing with my mod!

**Comment by QuasarQBH** [comment]
Thank you!!! If I found anymore, I will tell you again.
