### ISSUE TITLE
Traditional Chinese Translation

### ISSUE THREAD

**Issue by Edison12300** [mythridium/music#2]
The snare drum translation for Traditional Chinese should be "小軍鼓". The current translation is simplified chinese.
Thanks!

**Comment by mythridium** [comment]
Thanks so much for reporting this issue, I'm so sorry it took so long to fix this, I completely missed the issue request alert.

This is now fixed in v1.14.2 2a72405

**Comment by Edison12300** [comment]
I also noticed that the bard is also wrong. It should be "吟遊詩人".

**Comment by mythridium** [comment]
Thanks, I did a find and replace for the text for bard in the chinese traditional language file.

Hopefully this is all correct now, thanks!
