### ISSUE TITLE
[Bug] Crash due to missing potion

### ISSUE THREAD

**Issue by Chrisch3n** [mythridium/music#4]
There is a mod crash when I start training the music skill with a "missing/non-existing" potion equipped.

Likely Reason: 
I had "Generous Gratuity Potion III" (with charges left over) equipped in the Music skill. Then I trained the potion in Herblore to "Generous Gratuity Potion IV" and upgraded/sold the remaining "Generous Gratuity Potion III" while it was still equipped in Music. 
After the first complete training cycle (training bar reaches the end), the game likely wants to subtract 1 potion charge from "Generous Gratuity Potion III", which is not there anymore.
"Hot-swapping" from the non-existing "Generous Gratuity Potion III" to "Generous Gratuity Potion IV" also crashed the mod.

(Workaround)
Manually removing the "Generous Gratuity Potion III", (reloading, training without it for a cycle, reloading) and then equipping "Generous Gratuity Potion IV" seems to fix the issue. 

Version Mevor:  V1.3 (?11390)
Add-ons active: ToH + AoD

```
An error occurred while processing ticks:

Error due to the following mods:
[Myth] Music (v1.14.3)

Error Name: Error
Error Message: Tried to consume charge for action that does not have a potion in use.
Stack Trace:
consumeChargeForAction@https://melvoridle.com/assets/js/built/potionManager.js?11390:20:7
handler@https://melvoridle.com/assets/js/built/potionManager.js?11390:14:58
newHandler@https://melvoridle.com/assets/js/built/gameEvents.js?11390:5:8
emit/<@https://melvoridle.com/assets/js/mitt.min.js:1:421
emit@https://melvoridle.com/assets/js/mitt.min.js:1:404
get actionRewards@[Myth] Music:setup.mjs:1:44522
addActionRewards@https://melvoridle.com/assets/js/built/skill.js?11390:532:34
action@https://melvoridle.com/assets/js/built/skill.js?11390:530:52
GatheringSkill/this.actionTimer<@https://melvoridle.com/assets/js/built/skill.js?11390:508:125
tick@https://melvoridle.com/assets/js/built/combatManager.js?11390:373:89
activeTick@https://melvoridle.com/assets/js/built/skill.js?11390:515:55
tick@https://melvoridle.com/assets/js/built/game.js?11390:301:123
runTicks@https://melvoridle.com/assets/js/built/game.js?11390:299:96
processTime@https://melvoridle.com/assets/js/built/game.js?11390:298:6
loop@https://melvoridle.com/assets/js/built/game.js?11390:334:50


Active Action: mythMusic:Music
Current Equipment:
melvorD:Helmet: melvorD:Crown_of_Rhaelyx
melvorD:Platebody: melvorAoD:Peasant_Shirt
melvorD:Platelegs: melvorF:Potion_Makers_Leggings
melvorD:Boots: melvorF:Potion_Makers_Boots
melvorD:Shield: melvorF:Book_Of_Scholars
melvorD:Amulet: melvorD:Clue_Chasers_Insignia
melvorD:Ring: melvorD:Aorpheats_Signet_Ring
melvorD:Gloves: melvorF:Bobs_Gloves
melvorD:Quiver: melvorD:Dragon_Arrows
melvorD:Cape: melvorD:Firemaking_Skillcape
melvorD:Summon1: melvorF:Summoning_Familiar_Bear
melvorD:Summon2: melvorTotH:Summoning_Familiar_Owl
melvorD:Consumable: mythMusic:Music_Scroll_Of_XP
melvorD:Gem: melvorAoD:Lifesteal_Gem
melvorD:Enhancement3: melvorF:Undead_Enhancement_Superior

Action Information:
Is Active: true

Modding Enabled. Loaded mods:
[Myth] Combat Simulator
Mastery Pool Can Overflow
QuickShards
ETA
Shop Item Owned Indicator
Kills in Combat
Skill Boosts
Skip Township Casual Tasks For Free
Show Item Sources And Uses
Dungeon Pet Indicator
Item Owned Indicators
Combat Indicators
Right Click Equip Menu
Mastery XP Completion Percent
[Myth] Music
[Myth] Summoning
[Myth] Sidebar
Township UI QoL
Bypass Agility Costs Redone
Show Slayer Tier
```

**Comment by Chrisch3n** [comment]
Update: The error also occurs when only using "Generous Gratuity Potion IV", so it had nothing to do with the sold/upgraded portion like I suspected before. (Same error like above)


The workaround seems to be functioning: 
1. Unequip potion
2. Reload game
3. Train music skill without potion (Second reload not required)
4. Equip potion again
5. Train music as needed

Note: Reloading the game after the "workaround" with an active potion equipped causes the error again!

**Comment by mythridium** [comment]
Thanks so much for reporting this, unfortunately this was a bug introduced from combat sim.

I've release a fix for combat sim which resolves this issue. If the issue persists, feel free to create a new issue or comment on this one.
