### ISSUE TITLE
[Question] Concert Pass Half (A) & (B)

### ISSUE THREAD

**Issue by Chrisch3n** [mythridium/music#6]
Hi,

Can you please explain the Concert Pass a bit further and add the info to the documentation. 
I'm unsure when I receive Half (A) an (B). I know its 0.00075% but I don't know, if there are additional requirements:

- Can they be obtained during 1. any action, 2. only during non-combat actions, or 3. only while training music?
- Do Half (A) and Half (B) have different requirements?
- Do I need to wear something like the "Gold Topaz Ring" during actions like for the Signet Ring halfs is it independent like for the Crown of Rhaelyx components?
- Do they also drop during offline progression (Likely, but just to make sure)?

Thanks

PS: I really love your mod.

**Comment by mythridium** [comment]
Hi @Chrisch3n,

Thanks for your questions.

1. They only drop while training music.
2. They do not have any requirements to drop.
3. You do not have to wear the gold topaz ring, they do not have any requirements to drop.
4. Offline makes no difference in melvor idle, anything that happens online also happens offline.

**Comment by Chrisch3n** [comment]
Thanks for the quick response
